In [7]:
import pandas as pd
import numpy as np

In [11]:
edades=np.arange(10,50,2)
edades

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [12]:
categorias=np.where(edades>18,"Mayor","menor")
categorias

array(['menor', 'menor', 'menor', 'menor', 'menor', 'Mayor', 'Mayor',
       'Mayor', 'Mayor', 'Mayor', 'Mayor', 'Mayor', 'Mayor', 'Mayor',
       'Mayor', 'Mayor', 'Mayor', 'Mayor', 'Mayor', 'Mayor'], dtype='<U5')

In [14]:
subcategorias=np.where(edades<18,"Menor", np.where(edades<30,"adolescente","Adulto"))
print(edades)
subcategorias

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


array(['Menor', 'Menor', 'Menor', 'Menor', 'adolescente', 'adolescente',
       'adolescente', 'adolescente', 'adolescente', 'adolescente',
       'Adulto', 'Adulto', 'Adulto', 'Adulto', 'Adulto', 'Adulto',
       'Adulto', 'Adulto', 'Adulto', 'Adulto'], dtype='<U11')

In [20]:
valores,conteo=np.unique(subcategorias, return_counts=True)
print(valores)
conteo

['Adulto' 'Menor' 'adolescente']


array([10,  4,  6])

return counts se utiliza para saber el conteo de cuantas veces se repite en tu arreglo dicha palabra o numero
se utilizan dos variables por que en la primera te almacena los valores unicos que encontro
mientras que en la segunda te va a regresar el conteo de cada valor
para despues poder pasarlos a una lista mientras el metodo zip te miermite crear un diccionario donde las claves son los valores unicos y los valores el conteo que se hizo anteriormente


In [24]:
diccionario=dict(zip(valores,conteo))
diccionario

{np.str_('Adulto'): np.int64(10),
 np.str_('Menor'): np.int64(4),
 np.str_('adolescente'): np.int64(6)}